packages:
  - packages/*

catalog:
  '@antfu/eslint-config': ^4.16.2
  '@commitlint/cli': ^19.8.1
  '@commitlint/config-conventional': ^19.8.1
  '@dcloudio/uni-app': 3.0.0-alpha-4070520250704002
  '@dcloudio/uni-app-plus': 3.0.0-alpha-4070520250704002
  '@dcloudio/uni-h5': 3.0.0-alpha-4070520250704002
  '@dcloudio/uni-mp-weixin': 3.0.0-alpha-4070520250704002
  '@dcloudio/uni-uts-v1': 3.0.0-alpha-4070520250704002
  '@dcloudio/vite-plugin-uni': 3.0.0-alpha-4070520250704002
  '@iconify-json/carbon': ^1.2.10
  '@reactuses/core': ^6.0.5
  '@types/nprogress': ^0.2.3
  '@unocss/eslint-plugin': 66.0.0
  '@unocss/reset': 66.0.0
  eslint: ^9.30.1
  eslint-plugin-format: ^1.0.1
  lint-staged: ^16.1.2
  nprogress: ^0.2.0
  simple-git-hooks: ^2.13.0
  taze: ^19.1.0
  typescript: ^5.8.3
  vixt: ^0.5.4
  zustand: ^5.0.6
